
DEFINE(TNMS_LA_ATOM_NONE)			// エラー
DEFINE(TNMS_LA_ATOM_EOF)			// 終端

DEFINE(TNMS_LA_ATOM_ASSIGN)			// '='
DEFINE(TNMS_LA_ATOM_PLUS)			// '+'
DEFINE(TNMS_LA_ATOM_MINUS)			// '-'
DEFINE(TNMS_LA_ATOM_MULTIPLE)		// '*'
DEFINE(TNMS_LA_ATOM_DIVIDE)			// '/'
DEFINE(TNMS_LA_ATOM_PERCENT)		// '%'

DEFINE(TNMS_LA_ATOM_PLUS_ASSIGN)	// '+='
DEFINE(TNMS_LA_ATOM_MINUS_ASSIGN)	// '-='
DEFINE(TNMS_LA_ATOM_MULTIPLE_ASSIGN)// '*='
DEFINE(TNMS_LA_ATOM_DIVIDE_ASSIGN)	// '/='
DEFINE(TNMS_LA_ATOM_PERCENT_ASSIGN)	// '%='

DEFINE(TNMS_LA_ATOM_EQUAL)			// '=='
DEFINE(TNMS_LA_ATOM_NOT_EQUAL)		// '!='
DEFINE(TNMS_LA_ATOM_GREATER)		// '>'
DEFINE(TNMS_LA_ATOM_GREATER_EQUAL)	// '>='
DEFINE(TNMS_LA_ATOM_LESS)			// '<'
DEFINE(TNMS_LA_ATOM_LESS_EQUAL)		// '<='

DEFINE(TNMS_LA_ATOM_LOGICAL_AND)	// '&&'
DEFINE(TNMS_LA_ATOM_LOGICAL_OR)		// '||'

DEFINE(TNMS_LA_ATOM_DOT)			// '.'
DEFINE(TNMS_LA_ATOM_COMMA)			// ','
DEFINE(TNMS_LA_ATOM_COLON)			// ':'
DEFINE(TNMS_LA_ATOM_OPEN_PAREN)		// '('
DEFINE(TNMS_LA_ATOM_CLOSE_PAREN)	// ')'
DEFINE(TNMS_LA_ATOM_OPEN_BRACKET)	// '['
DEFINE(TNMS_LA_ATOM_CLOSE_BRACKET)	// ']'
DEFINE(TNMS_LA_ATOM_OPEN_BRACE)		// '{'
DEFINE(TNMS_LA_ATOM_CLOSE_BRACE)	// '}'

DEFINE(TNMS_LA_ATOM_OPEN_SUMI)		// '【'
DEFINE(TNMS_LA_ATOM_CLOSE_SUMI)		// '】'

DEFINE(TNMS_LA_ATOM_VAL_INT)		// 直値整数
DEFINE(TNMS_LA_ATOM_VAL_STR)		// 直値文字列

DEFINE(TNMS_LA_ATOM_LABEL)			// ラベル
DEFINE(TNMS_LA_ATOM_Z_LABEL)		// Ｚラベル
DEFINE(TNMS_LA_ATOM_COMMAND)		// command
DEFINE(TNMS_LA_ATOM_PROPERTY)		// property
DEFINE(TNMS_LA_ATOM_GOTO)			// goto
DEFINE(TNMS_LA_ATOM_GOSUB)			// gosub
DEFINE(TNMS_LA_ATOM_GOSUBSTR)		// gosubstr
DEFINE(TNMS_LA_ATOM_RETURN)			// return
DEFINE(TNMS_LA_ATOM_IF)				// if
DEFINE(TNMS_LA_ATOM_ELSEIF)			// elseif
DEFINE(TNMS_LA_ATOM_ELSE)			// else
DEFINE(TNMS_LA_ATOM_FOR)			// for
DEFINE(TNMS_LA_ATOM_WHILE)			// while
DEFINE(TNMS_LA_ATOM_CONTINUE)		// continue
DEFINE(TNMS_LA_ATOM_BREAK)			// break
DEFINE(TNMS_LA_ATOM_SWITCH)			// switch
DEFINE(TNMS_LA_ATOM_CASE)			// case
DEFINE(TNMS_LA_ATOM_DEFAULT)		// default

DEFINE(TNMS_LA_ATOM_UNKNOWN)		// 未定義語

DEFINE(TNMS_LA_ATOM_TILDE)			// '~'
DEFINE(TNMS_LA_ATOM_AND)			// '&'
DEFINE(TNMS_LA_ATOM_OR)				// '|'
DEFINE(TNMS_LA_ATOM_HAT)			// '^'
DEFINE(TNMS_LA_ATOM_SL)				// '<<'
DEFINE(TNMS_LA_ATOM_SR)				// '>>'

DEFINE(TNMS_LA_ATOM_AND_ASSIGN)		// '&='
DEFINE(TNMS_LA_ATOM_OR_ASSIGN)		// '|='
DEFINE(TNMS_LA_ATOM_HAT_ASSIGN)		// '^='
DEFINE(TNMS_LA_ATOM_SL_ASSIGN)		// '<<='
DEFINE(TNMS_LA_ATOM_SR_ASSIGN)		// '>>='

DEFINE(TNMS_LA_ATOM_SR3)			// '>>>'
DEFINE(TNMS_LA_ATOM_SR3_ASSIGN)		// '>>>='
