#pragma		once

// ****************************************************************
// プロセスのフレーム処理
// ================================================================

// 各種プロセスのフレーム処理
bool	tnm_game_start_wipe_proc();
bool	tnm_game_end_wipe_proc();
bool	tnm_game_timer_start_proc();
bool	tnm_load_proc();
bool	tnm_easy_load_proc();
bool	tnm_quick_load_proc();
bool	tnm_end_load_proc();
bool	tnm_inner_load_proc();
bool	tnm_backlog_load_proc();
bool	tnm_return_to_menu_proc();
bool	tnm_return_to_sel_proc();
bool	tnm_time_wait_proc();
bool	tnm_key_wait_proc();
bool	tnm_counter_wait_proc();
bool	tnm_object_event_wait_proc();
bool	tnm_object_event_all_wait_proc();
bool	tnm_mwnd_open_wait_proc();
bool	tnm_mwnd_close_wait_proc();
bool	tnm_mwnd_close_wait_all_proc();
bool	tnm_message_wait_proc();
bool	tnm_message_key_wait_proc();
bool	tnm_novel_r_proc();
bool	tnm_bgm_wait_proc();
bool	tnm_bgm_fade_out_wait_proc();
bool	tnm_koe_wait_proc();
bool	tnm_pcm_wait_proc();
bool	tnm_pcmch_wait_proc();
bool	tnm_pcmch_fade_out_wait_proc();
bool	tnm_pcm_event_wait_proc();
bool	tnm_mov_wait_proc();
bool	tnm_wipe_wait_proc();
bool	tnm_shake_wait_proc();
bool	tnm_quake_wait_proc();
bool	tnm_event_wait_proc();
bool	tnm_all_event_wait_proc();
bool	tnm_obj_mov_wait_proc();
bool	tnm_obj_emote_wait_proc();
bool	tnm_sel_proc();
bool	tnm_sel_btn_proc();
bool	tnm_sel_btn_obj_proc();
bool	tnm_save_dialog_proc();
bool	tnm_end_save_proc();
bool	tnm_end_game_proc();
bool	tnm_start_warning_proc();
bool	tnm_tweet_capture_after_proc();
