#pragma		once

#include	"dialog/cfg_wnd_solo_screen.h"
#include	"dialog/cfg_wnd_solo_font_msgspd.h"
#include	"dialog/cfg_wnd_solo_font.h"
#include	"dialog/cfg_wnd_solo_msgspd.h"
#include	"dialog/cfg_wnd_solo_volume_bgmfade.h"
#include	"dialog/cfg_wnd_solo_volume.h"
#include	"dialog/cfg_wnd_solo_bgmfade.h"
#include	"dialog/cfg_wnd_solo_koemode_chrkoe.h"
#include	"dialog/cfg_wnd_solo_koemode.h"
#include	"dialog/cfg_wnd_solo_chrkoe.h"
#include	"dialog/cfg_wnd_solo_mwndbk.h"
#include	"dialog/cfg_wnd_solo_automode.h"
#include	"dialog/cfg_wnd_solo_jitan.h"
#include	"dialog/cfg_wnd_solo_else.h"
#include	"dialog/cfg_wnd_solo_system.h"
#include	"dialog/cfg_wnd_solo_movtype.h"

#include	"dialog/sys_wnd_solo_save.h"
#include	"dialog/sys_wnd_solo_load.h"
#include	"dialog/sys_wnd_solo_tweet.h"

#include	"dialog/cfg_wnd_modal_screen.h"
#include	"dialog/cfg_wnd_modal_font_msgspd.h"
#include	"dialog/cfg_wnd_modal_font.h"
#include	"dialog/cfg_wnd_modal_msgspd.h"
#include	"dialog/cfg_wnd_modal_volume_bgmfade.h"
#include	"dialog/cfg_wnd_modal_volume.h"
#include	"dialog/cfg_wnd_modal_bgmfade.h"
#include	"dialog/cfg_wnd_modal_koemode_chrkoe.h"
#include	"dialog/cfg_wnd_modal_koemode.h"
#include	"dialog/cfg_wnd_modal_chrkoe.h"
#include	"dialog/cfg_wnd_modal_mwndbk.h"
#include	"dialog/cfg_wnd_modal_automode.h"
#include	"dialog/cfg_wnd_modal_jitan.h"
#include	"dialog/cfg_wnd_modal_else.h"
#include	"dialog/cfg_wnd_modal_system.h"
#include	"dialog/cfg_wnd_modal_movtype.h"

#include	"dialog/sys_wnd_modal_save.h"
#include	"dialog/sys_wnd_modal_load.h"

#include	"dialog/cfg_wnd_config_base.h"
#include	"dialog/cfg_wnd_config_base_full_mode.h"
