//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// SiglusCompiler.rc で使用
//
#define IDD_TNSC                        101
#define IDD_TNMY_COMPILER               101
#define IDD_TNM_COMPILER                101
#define IDR_MENU                        102
#define IDD_DIALOG1                     103
#define IDD_CONFIG_PAGE_00              103
#define IDD_PROJECT_SETTING             105
#define IDI_ICON1                       106
#define IDC_BTN_COMPILE                 1002
#define IDC_EDT_TNS                     1003
#define IDC_EDT_CA                      1004
#define IDC_EDT_TMP                     1004
#define IDC_LIST1                       1005
#define IDC_LV_TNS                      1005
#define IDC_LV_INC                      1005
#define IDC_LV_LOG                      1006
#define IDC_EDT_OUT                     1007
#define IDC_LV_SCN2                     1007
#define IDC_LV_SCN                      1007
#define IDC_STC_TNS                     1008
#define IDC_LV_INI                      1008
#define IDC_STC_TMP                     1009
#define IDC_STC_OUT                     1010
#define IDC_EDT_EXE                     1011
#define IDC_STC_EXE                     1012
#define IDC_BTN_RUN                     1013
#define IDC_EDT_EDITOR                  1014
#define IDC_BTN_RUN2                    1014
#define IDC_BTN_MANUAL                  1014
#define IDC_STC_EDITOR                  1015
#define IDC_BTN_AUTO_FIND               1016
#define IDC_BTN_SEL_AUTO                1016
#define IDC_BTN_SEL_ALL                 1017
#define IDC_BTN_ALL_SEL_ALL             1017
#define IDC_BTN_FIND                    1018
#define IDC_CMB_PROJECT                 1019
#define IDC_BUTTON1                     1020
#define IDC_BTN_NEW_PROJECT             1020
#define IDC_BTN_OK                      1020
#define IDC_BTN_NEW_PROJECT2            1021
#define IDC_BTN_PROJECT_CONFIG          1021
#define IDC_BTN_CANCEL                  1021
#define IDC_EDT_TMP_PATH                1022
#define IDC_BTN_FIND2                   1022
#define IDC_BTN_ALL                     1022
#define IDC_BTN_ALL_SEL_AUTO            1022
#define IDC_EDT_OUT_PATH                1023
#define IDC_BTN_DEL_PROJECT             1023
#define IDC_STC_OUT_PATH                1024
#define IDC_STC_TMP_PATH                1025
#define IDC_EDT_OUT_PATH2               1026
#define IDC_EDT_OUT_PATH_NOANGOU        1026
#define IDC_EDT_PROJECT_NAME            1027
#define IDC_STC_PROJECT_NAME            1028
#define IDC_STC_EXE_PATH                1029
#define IDC_EDT_EXE_PATH                1030
#define IDC_STC_EDITOR_PATH             1031
#define IDC_EDT_EDITOR_PATH             1032
#define IDC_EDT_SCN_PATH                1033
#define IDC_STC_SCN_PATH                1034
#define IDC_STC_VERSION                 1035
#define IDC_STC_MANUAL_PATH             1035
#define IDC_EDT_MANUAL_PATH             1036
#define IDC_EDIT1                       1037
#define IDC_EDT_STATUS                  1037
#define IDC_EDT_WORK_PATH               1037
#define IDC_CHK_START_SCENE             1038
#define IDC_STC_WORK_PATH               1038
#define IDC_EDT_START_SCENE             1039
#define IDC_EDT_ANGOU_STR               1039
#define IDC_STC_OUT_PATH_NOANGOU        1039
#define IDC_CHK_EXECUTE                 1040
#define IDC_EDT_GAMEEXE_INI             1040
#define IDC_CHK_DEBUG_ON                1041
#define IDC_EDT_EXTEND_INC              1041
#define IDC_CHK_DEBUG_OFF               1042
#define IDC_EDT_GAMEEXE_DAT             1042
#define IDC_EDT_START_Z_NO              1043
#define IDC_EDT_SCENE_PCK               1043
#define IDC_STC_DRAGDROP                1044
#define IDC_EDT_STATUS2                 1044
#define IDC_EDT_DETAIL                  1044
#define IDC_SPN_START_Z_NO              1045
#define IDC_CHK_TEST                    1046
#define IDC_CHK_NO_INTERVAL             1047
#define IDC_CHK_NO_INTERVAL2            1048
#define IDC_CHK_EASY_LINK               1048
#define IDC_BTN_EXPLAIN_UNDER           1049
#define IDC_CHK_NO_INTERVAL3            1050
#define IDC_CHK_OVERFLOW_ERROR_OFF      1050
#define IDC_CHK_UTF8                    1050
#define IDC_STC_GAMEEXE_INI             1051
#define IDC_STC_EXTEND_INC              1052
#define IDC_GRP_EXTEND                  1053
#define IDC_GRP_EXTEND2                 1054
#define IDC_GRP_OUTPUT                  1054
#define IDC_STC_GAMEEXE_DAT             1055
#define IDC_STC_SCENE_PCK               1056
#define ID_40001                        40001
#define IDM_EXE_ANGOU_MANUAL            40002
#define IDM_EXE_ANGOU_FUNC              40003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
