//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// Siglus.rc で使用
//
#define IDD_CFG_WIN_BASE                101
#define IDD_CFG_WIN_BASE_ELSE           104
#define IDD_CFG_WIN_BASE_JITAN          106
#define IDD_CFG_WIN_BASE_MWNDBK         109
#define IDD_CFG_WIN_BASE_SCREEN         110
#define IDD_CFG_WIN_BASE_SYSTEM         112
#define IDD_CFG_WIN_SOLO_ELSE           118
#define IDD_CFG_WIN_SOLO_JITAN          121
#define IDD_CFG_WIN_SOLO_MOVTYPE        124
#define IDD_CFG_WIN_SOLO_MWNDBK         126
#define IDD_CFG_WIN_SOLO_SCREEN         127
#define IDD_CFG_WIN_SOLO_SUPPORT_MOVTYPE 129
#define IDD_CFG_WIN_SOLO_SYSTEM         130
#define IDD_DB_WIN_INFO_CG_TABLE        133
#define IDD_DB_WIN_INFO_DEBUG           134
#define IDD_DB_WIN_INFO_ERROR           135
#define IDD_DB_WIN_INFO_FLAG            136
#define IDD_DB_WIN_INFO_MWND            137
#define IDD_DB_WIN_INFO_OBJECT          138
#define IDD_DB_WIN_INFO_READ_FLAG       139
#define IDD_DB_WIN_INFO_SCN_CONTROL     140
#define IDD_DB_WIN_INFO_SWITCH          141
#define IDD_DB_WIN_INFO_TEST            142
#define IDD_DB_WIN_INFO_TRACE           143
#define IDD_DEFINE                      144
#define IDD_DUMMY                       145
#define IDD_SYS_WIN_SOLO_SAVELOAD       146
#define IDD_CHANGE_RESOLUTION_WARNING   148
#define IDD_DB_WIN_INFO_ELEMENT         149
#define IDD_SYS_WIN_SOLO_INFO           150
#define IDD_DB_WIN_INFO_NAMAE_FLAG      151
#define IDR_EFFECT1                     153
#define IDD_DB_WIN_INFO_KOE             154
#define IDD_CFG_WIN_SOLO_SCREEN_EN      155
#define IDD_CFG_WIN_BASE_SCREEN_EN      156
#define IDD_CFG_WIN_BASE_EN             158
#define IDD_CHANGE_RESOLUTION_WARNING_EN 159
#define IDD_CFG_WIN_SOLO_MSGSPD1        162
#define IDD_CFG_WIN_BASE_SYSTEM_EN      165
#define IDD_CFG_WIN_SOLO_SYSTEM_EN      166
#define IDD_CFG_WIN_SOLO_MOVTYPE_EN     167
#define IDD_CFG_WIN_BASE_MWNDBK_EN      168
#define IDD_CFG_WIN_SOLO_MWNDBK_EN      169
#define IDD_CFG_WIN_BASE_VOLUME1        170
#define IDD_CFG_WIN_SOLO_VOLUME_BGMFADE1 174
#define IDD_TWEET                       175
#define IDD_DIALOG1                     176
#define IDD_TWITTER_AUTHORIZE           176
#define IDD_CFG_WIN_BASE_SYSTEM_ES      177
#define IDD_CFG_WIN_SOLO_SCREEN_ZH      178
#define IDD_CFG_WIN_BASE_SCREEN_ZH      179
#define IDD_CFG_WIN_BASE_ZH             180
#define IDD_TWEET_ID                    182
#define IDD_SYS_WIN_SOLO_SAVELOAD_FR    183
#define IDD_SYS_WIN_SOLO_SAVELOAD_ID    184
#define IDD_CFG_WIN_BASE_MWNDBK_ZH      185
#define IDD_CFG_WIN_SOLO_MWNDBK_ZH      186
#define IDD_CHANGE_RESOLUTION_WARNING_ID 187
#define IDD_CHANGE_RESOLUTION_WARNING_FR 188
#define IDD_CFG_WIN_SOLO_SYSTEM_ID      189
#define IDD_CFG_WIN_SOLO_SYSTEM_FR      190
#define IDD_CFG_WIN_SOLO_SCREEN_ID      191
#define IDD_CFG_WIN_SOLO_SCREEN_FR      192
#define IDD_CFG_WIN_BASE_SYSTEM_ZH      193
#define IDD_CFG_WIN_SOLO_MOVTYPE_ZH     194
#define IDD_CFG_WIN_SOLO_SYSTEM_ZH      195
#define IDD_CHANGE_RESOLUTION_WARNING_ZH 196
#define IDD_CFG_WIN_SOLO_MWNDBK_ID      197
#define IDD_CFG_WIN_SOLO_MWNDBK_FR      198
#define IDD_CFG_WIN_SOLO_JITAN_ZH       199
#define IDD_CFG_WIN_SOLO_MOVTYPE_ID     200
#define IDD_CFG_WIN_SOLO_MOVTYPE_FR     201
#define IDD_CFG_WIN_BASE_JITAN_ZH       202
#define IDD_CFG_WIN_SOLO_JITAN_ID       203
#define IDD_CFG_WIN_SOLO_JITAN_FR       204
#define IDD_CFG_WIN_BASE_ELSE_ZH        205
#define IDD_CFG_WIN_BASE_ELSE1          206
#define IDD_CFG_WIN_BASE_ELSE_EN        206
#define IDD_SYS_WIN_SOLO_SAVELOAD_DE    207
#define IDD_CFG_WIN_BASE_DE             208
#define IDD_CFG_WIN_SOLO_ELSE_ID        209
#define IDD_CFG_WIN_SOLO_ELSE_FR        210
#define IDD_CFG_WIN_BASE_SYSTEM_DE      211
#define IDD_CFG_WIN_BASE_SCREEN_DE      212
#define IDD_CFG_WIN_SOLO_SCREEN_DE      213
#define IDD_CFG_WIN_SOLO_COMMON_ID      214
#define IDD_CFG_WIN_SOLO_COMMON_FR      215
#define IDD_CFG_WIN_BASE_SYSTEM_ID      216
#define IDD_CFG_WIN_BASE_SYSTEM_FR      217
#define IDD_CFG_WIN_BASE_SCREEN_ID      218
#define IDD_CFG_WIN_BASE_SCREEN_FR      219
#define IDD_CFG_WIN_BASE_MWNDBK_ID      220
#define IDD_CFG_WIN_BASE_MWNDBK_FR      221
#define IDD_CFG_WIN_BASE_JITAN_ID       222
#define IDD_CFG_WIN_BASE_MWNDBK_DE      223
#define IDD_CFG_WIN_SOLO_MWNDBK_DE      224
#define IDD_CFG_WIN_BASE_JITAN_FR       225
#define IDD_CFG_WIN_BASE_ELSE_ID        226
#define IDD_CFG_WIN_BASE_ELSE_FR        227
#define IDD_CFG_WIN_SOLO_JITAN_DE       229
#define IDD_CFG_WIN_BASE_JITAN_DE       230
#define IDD_CFG_WIN_SOLO_SYSTEM_DE      231
#define IDD_CFG_WIN_SOLO_MOVTYPE_DE     232
#define IDD_CFG_WIN_BASE_ELSE_DE        233
#define IDD_CFG_WIN_BASE_ID             235
#define IDD_CHANGE_RESOLUTION_WARNING_DE 236
#define IDD_CFG_WIN_SOLO_ELSE_DE        237
#define IDD_CFG_WIN_BASE_COMMON         238
#define IDD_CFG_WIN_BASE_COMMON_DE      239
#define IDD_CFG_WIN_SOLO_AUTOMODE1      240
#define IDD_CFG_WIN_SOLO_COMMON         240
#define IDD_CFG_WIN_BASE_COMMON_EN      241
#define IDD_CFG_WIN_BASE_COMMON_ZH      242
#define IDD_CFG_WIN_SOLO_COMMON_EN      243
#define IDD_CFG_WIN_SOLO_COMMON_DE      244
#define IDD_CFG_WIN_SOLO_COMMON_ZH      245
#define IDD_TWEET_DE                    246
#define IDD_CFG_WIN_BASE_COMMON_ZHTW    247
#define IDD_CFG_WIN_SOLO_COMMON_ZHTW    248
#define IDD_CFG_WIN_BASE_ZHTW           249
#define IDD_CFG_WIN_BASE_ELSE_ZHTW      250
#define IDD_CFG_WIN_BASE_JITAN_ZHTW     251
#define IDD_CFG_WIN_BASE_MWNDBK_ZHTW    252
#define IDD_CFG_WIN_BASE_SCREEN_ZHTW    253
#define IDD_CFG_WIN_BASE_SYSTEM_ZHTW    254
#define IDD_CFG_WIN_SOLO_JITAN_ZHTW     255
#define IDD_CFG_WIN_SOLO_MOVTYPE_ZHTW   256
#define IDD_CFG_WIN_SOLO_MWNDBK_ZHTW    257
#define IDD_CFG_WIN_SOLO_SCREEN_ZHTW    258
#define IDD_CFG_WIN_SOLO_SYSTEM_ZHTW    259
#define IDD_CHANGE_RESOLUTION_WARNING_ZHTW 260
#define IDD_TWEET_ZHTW                  261
#define IDD_CFG_WIN_BASE_COMMON_ES      262
#define IDD_CFG_WIN_BASE_ES             263
#define IDD_CFG_WIN_BASE_ELSE_ES        264
#define IDD_CFG_WIN_BASE_JITAN_ES       265
#define IDD_CFG_WIN_BASE_MWNDBK_ES      266
#define IDD_CFG_WIN_BASE_SCREEN_ES      267
#define IDD_CFG_WIN_SOLO_COMMON_ES      268
#define IDD_CFG_WIN_SOLO_ELSE_ES        269
#define IDD_CFG_WIN_SOLO_JITAN_ES       270
#define IDD_CFG_WIN_SOLO_MOVTYPE_ES     271
#define IDD_CFG_WIN_SOLO_MWNDBK_ES      272
#define IDD_CFG_WIN_SOLO_SCREEN_ES      273
#define IDD_CFG_WIN_SOLO_SYSTEM_ES      274
#define IDD_CHANGE_RESOLUTION_WARNING_ES 275
#define IDD_SYS_WIN_SOLO_SAVELOAD_ES    276
#define IDD_TWEET_ES                    277
#define IDD_CFG_WIN_BASE_FR             278
#define IDD_TWEET_FR                    281
#define IDD_CFG_WIN_BASE_COMMON_FR      282
#define IDD_CFG_WIN_BASE_COMMON_ID      283
#define IDC_BTN_ALL_CONFIG_INIT         1001
#define IDC_BTN_CLOSE                   1010
#define IDC_BTN_ELSE_CLOSE              1011
#define IDC_BTN_ELSE_INIT               1012
#define IDC_BTN_FIND_NOT_READ           1013
#define IDC_BTN_FULLSCREEN_CUSTOM_MOVE_LR 1016
#define IDC_BTN_FULLSCREEN_CUSTOM_MOVE_UD 1017
#define IDC_BTN_FULLSCREEN_CUSTOM_SCALE_LR 1018
#define IDC_BTN_FULLSCREEN_CUSTOM_SCALE_UD 1019
#define IDC_BTN_FULLSCREEN_INIT         1020
#define IDC_BTN_JITAN_CLOSE             1021
#define IDC_BTN_CHANGE_RESOLUTION_INFO  1021
#define IDC_BTN_JITAN_INIT              1022
#define IDC_BTN_CHANGE_RESOLUTION       1022
#define IDC_BTN_MOVTYPE_CANCEL          1025
#define IDC_BTN_MOVTYPE_CLOSE           1026
#define IDC_BTN_MOVTYPE_DESIDE          1027
#define IDC_BTN_MWNDBK_CLOSE            1030
#define IDC_BTN_MWNDBK_INIT             1031
#define IDC_BTN_NEW                     1032
#define IDC_BTN_NEXT                    1033
#define IDC_BTN_RESTART                 1034
#define IDC_BTN_SAVELOAD                1035
#define IDC_BTN_SCREEN_CLOSE            1036
#define IDC_BTN_SELECT_START            1037
#define IDC_BTN_SYSTEM_CLOSE            1038
#define IDC_BTN_SYSTEM_INIT             1039
#define IDC_CHK_BREAK                   1043
#define IDC_CHK_CLICK                   1044
#define IDC_CHK_DBLCLICK                1045
#define IDC_CHK_FULLSCREEN_CUSTOM_SCALE 1047
#define IDC_CHK_JITAN_AUTOMODE          1048
#define IDC_CHK_JITAN_MSGBK             1049
#define IDC_CHK_JITAN_NORMAL            1050
#define IDC_CHK_SWITCH00                1052
#define IDC_CHK_SWITCH01                1053
#define IDC_CHK_SWITCH02                1054
#define IDC_CHK_SWITCH03                1055
#define IDC_CHK_SWITCH04                1056
#define IDC_CHK_SWITCH05                1057
#define IDC_CHK_SWITCH06                1058
#define IDC_CHK_SWITCH07                1059
#define IDC_CHK_SWITCH08                1060
#define IDC_CHK_SWITCH09                1061
#define IDC_CHK_SYSTEM_KOE_DONT_STOP    1062
#define IDC_CHK_SYSTEM_NO_MWND_ANIME    1063
#define IDC_CHK_SYSTEM_NO_WIPE_ANIME    1064
#define IDC_CHK_SYSTEM_SKIP_UNREAD_MESSAGE 1065
#define IDC_CHK_SYSTEM_SKIP_WIPE_ANIME  1066
#define IDC_CHK_SYSTEM_SLEEP            1067
#define IDC_CHK_SYSTEM_WHEEL_NEXT_MESSAGE 1068
#define IDC_CHK_TRACE                   1069
#define IDC_CHK_SYSTEM_PLAY_SILENT_SOUND 1069
#define IDC_CHK_WARNING                 1075
#define IDC_CHK_VOLUME_SE2              1075
#define IDC_CMB_FONT_SIZE               1076
#define IDC_EDT_EDITOR                  1077
#define IDC_EDT_NUM00                   1078
#define IDC_EDT_NUM01                   1079
#define IDC_EDT_NUM02                   1080
#define IDC_EDT_NUM03                   1081
#define IDC_EDT_NUM04                   1082
#define IDC_EDT_NUM05                   1083
#define IDC_EDT_NUM06                   1084
#define IDC_EDT_NUM07                   1085
#define IDC_EDT_NUM08                   1086
#define IDC_EDT_NUM09                   1087
#define IDC_EDT_SS                      1088
#define IDC_EDT_STR00                   1089
#define IDC_EDT_KOE                     1089
#define IDC_EDT_STR01                   1090
#define IDC_EDT_KOE2                    1090
#define IDC_EDT_KOE_TOOL                1090
#define IDC_EDT_STR02                   1091
#define IDC_EDT_STR03                   1092
#define IDC_EDT_STR04                   1093
#define IDC_EDT_STR05                   1094
#define IDC_EDT_STR06                   1095
#define IDC_EDT_STR07                   1096
#define IDC_EDT_STR08                   1097
#define IDC_EDT_STR09                   1098
#define IDC_END                         1099
#define IDC_GRP_FULLSCREEN_CUSTOM       1107
#define IDC_GRP_FULLSCREEN_DISP         1108
#define IDC_GRP_FULLSCREEN_DISPLAY      1109
#define IDC_GRP_FULLSCREEN_RESOLUTION   1110
#define IDC_GRP_JITAN                   1111
#define IDC_GRP_MWNDBK                  1114
#define IDC_GRP_SCREEN_MODE             1115
#define IDC_GRP_SYSTEM                  1116
#define IDC_GRP_SYSTEM_MOVIE            1117
#define IDC_GRP_WINDOW_SIZE             1124
#define IDC_LST_FULLSCREEN_DISPLAY      1127
#define IDC_LST_FULLSCREEN_RESOLUTION   1128
#define IDC_LST_GROUP                   1129
#define IDC_LST_ORIGINAL                1130
#define IDC_LST_SAVELOAD                1131
#define IDC_LST_SCN_NAME                1132
#define IDC_LST_Z_NO                    1133
#define IDC_LV                          1134
#define IDC_LV_A                        1135
#define IDC_LV_B                        1136
#define IDC_LV_BACK                     1137
#define IDC_LV_C                        1138
#define IDC_LV_D                        1139
#define IDC_LV_E                        1140
#define IDC_LV_F                        1141
#define IDC_LV_FRONT                    1142
#define IDC_LV_G                        1143
#define IDC_LV_K                        1144
#define IDC_LV_L                        1145
#define IDC_LV_M                        1146
#define IDC_LV_NEXT                     1147
#define IDC_LV_READ_FLAG                1148
#define IDC_LV_S                        1149
#define IDC_LV_SCN                      1150
#define IDC_LV_Z                        1151
#define IDC_RAD_FULLSCREEN_DISP_CUSTOM  1155
#define IDC_RAD_FULLSCREEN_DISP_FIT     1156
#define IDC_RAD_FULLSCREEN_DISP_LRFIT   1157
#define IDC_RAD_FULLSCREEN_DISP_NORMAL  1158
#define IDC_RAD_FULLSCREEN_DISP_UDFIT   1159
#define IDC_RAD_FULLSCREEN_DISP_UDLRFIT 1160
#define IDC_RAD_MOVTYPE_MCI             1164
#define IDC_RAD_MOVTYPE_WMP             1165
#define IDC_RAD_SCREEN_MODE_FULLSCREEN  1166
#define IDC_RAD_SCREEN_MODE_WINDOW      1167
#define IDC_RAD_SYSTEM_MOVIE_PLAY_TYPE_MCI 1168
#define IDC_RAD_SYSTEM_MOVIE_PLAY_TYPE_WMP 1169
#define IDC_RAD_WINDOW_SIZE_050         1170
#define IDC_RAD_WINDOW_SIZE_075         1171
#define IDC_RAD_WINDOW_SIZE_100         1172
#define IDC_RAD_WINDOW_SIZE_150         1173
#define IDC_RAD_WINDOW_SIZE_200         1174
#define IDC_SLD_FULLSCREEN_CUSTOM_MOVE_LR 1179
#define IDC_SLD_FULLSCREEN_CUSTOM_MOVE_UD 1180
#define IDC_SLD_FULLSCREEN_CUSTOM_SCALE_LR 1181
#define IDC_SLD_FULLSCREEN_CUSTOM_SCALE_UD 1182
#define IDC_SLD_JITAN                   1183
#define IDC_SLD_MWNDBK_B                1185
#define IDC_SLD_MWNDBK_G                1186
#define IDC_SLD_MWNDBK_R                1187
#define IDC_SLD_MWNDBK_TR               1188
#define IDC_SPN_NUM00                   1194
#define IDC_SPN_NUM01                   1195
#define IDC_SPN_NUM02                   1196
#define IDC_SPN_NUM03                   1197
#define IDC_SPN_NUM04                   1198
#define IDC_SPN_NUM05                   1199
#define IDC_SPN_NUM06                   1200
#define IDC_SPN_NUM07                   1201
#define IDC_SPN_NUM08                   1202
#define IDC_SPN_NUM09                   1203
#define IDC_STC_EDITOR                  1210
#define IDC_STC_FULLSCREEN_CUSTOM_MOVE_LR 1212
#define IDC_STC_FULLSCREEN_CUSTOM_MOVE_LR_VAL 1213
#define IDC_STC_FULLSCREEN_CUSTOM_MOVE_UD 1214
#define IDC_STC_FULLSCREEN_CUSTOM_MOVE_UD_VAL 1215
#define IDC_STC_FULLSCREEN_CUSTOM_SCALE_LR 1216
#define IDC_STC_FULLSCREEN_CUSTOM_SCALE_LR_VAL 1217
#define IDC_STC_FULLSCREEN_CUSTOM_SCALE_UD 1218
#define IDC_STC_FULLSCREEN_CUSTOM_SCALE_UD_VAL 1219
#define IDC_STC_GAME_VERSION            1220
#define IDC_STC_FULLSCREEN_DISPLAY      1220
#define IDC_STC_JITAN_2BAI              1221
#define IDC_STC_FULLSCREEN_RESOLUTION   1221
#define IDC_STC_JITAN_3BAI              1222
#define IDC_STC_JITAN_NORMAL            1223
#define IDC_STC_MOVTYPE_MESS00          1224
#define IDC_STC_MOVTYPE_MESS01          1225
#define IDC_STC_MWNDBK_B                1229
#define IDC_STC_MWNDBK_G                1230
#define IDC_STC_MWNDBK_R                1231
#define IDC_STC_MWNDBK_TR               1232
#define IDC_STC_SS                      1233
#define IDC_STC_STATUS                  1234
#define IDC_STC_KOE                     1234
#define IDC_TAB                         1235
#define IDC_STC_KOE_TOOL                1235
#define IDC_TAB_BASE                    1236
#define IDC_TAB_SAVELOAD                1237
#define IDC_CHK_FULLSCREEN_CHANGE_RESOLUTION 1238
#define IDC_CMB_FULLSCREEN_RESOLUTION   1239
#define IDC_CMB_FULLSCREEN_DISPLAY      1240
#define IDC_GRP_FULLSCREEN_DETAIL       1241
#define IDC_CHANGE_RESOLUTION_OK        1242
#define IDC_CHANGE_RESOLUTION_CANCEL    1243
#define IDC_STC_CHANGE_RESOLUTION_TEXT  1244
#define IDC_CHK_ONLY_ERROR              1245
#define IDC_TR_ELEMENT                  1246
#define IDC_LV_ELEMENT                  1247
#define IDC_LIST1                       1248
#define IDC_LV_LIST                     1248
#define IDC_LV_OBJECT_LIST              1249
#define IDC_LV_MWND_LIST                1250
#define IDC_LV_INT_LIST                 1251
#define IDC_LV_STR_LIST                 1252
#define IDC_LV_STR_LIST2                1253
#define IDC_LV_COUNTER_LIST             1253
#define IDC_LV_PCMCH_LIST               1254
#define IDC_BTN_OPEN_LIST               1255
#define IDC_BTN_OPEN_ELEMENT            1256
#define IDC_BTN_CLIPBOARD               1256
#define IDC_LV_PCM_EVENT_LIST           1257
#define IDC_EDT_INFO                    1257
#define IDC_LV_CALL_LIST                1258
#define IDC_LV_GLOBAL                   1258
#define IDC_LV_GROUP_LIST               1259
#define IDC_LV_LOCA                     1259
#define IDC_LV_QUAKE_LIST               1260
#define IDC_LV_LOCAL                    1260
#define IDC_LV_FRAME_ACTION_LIST        1261
#define IDC_BTN_OPEN                    1261
#define IDC_LV_WORLD_LIST               1262
#define IDC_LV_MASK_LIST                1263
#define IDC_LV_EFFECT_LIST              1264
#define IDC_PRG_KOE                     1268
#define IDC_PCT_KOE                     1270
#define IDC_STC_PCT_KOE_RECT            1271
#define IDC_STC_BITMAP                  1272
#define IDC_BTN_TWEET                   1273
#define IDC_BTN_AUTHORIZE               1274
#define IDC_EDT_TWEET_TEXT              1275
#define IDC_STC_USER_NAME               1276
#define IDC_STC_KOE_LENGTH              1277
#define IDC_STC_KOE_NOW                 1279
#define IDC_BTN_COPY                    1280
#define IDC_CHK_COPY_BY_CLICK           1281
#define IDC_CHK_COPY                    1281

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        284
#define _APS_NEXT_COMMAND_VALUE         40000
#define _APS_NEXT_CONTROL_VALUE         1282
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
